"""empty message

Revision ID: 775302bfc349
Revises: b8a94abb94a6
Create Date: 2022-01-24 11:15:07.012245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775302bfc349'
down_revision = 'b8a94abb94a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
